name: Release
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Specify the stage to release'
        required: true
        default: 'staging'
jobs:
  release:
    name: Release to server
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: soap

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Set Variables
        uses: allenevans/set-env@v2.0.0
        with:
          OVPN: ${{ secrets.OVPN}}

      - name: Write VPN Files
        run: |
          mkdir -p ~/.ssh
          echo "$OVPN" > .github/vpn.ovpn

      - name: Install Open VPN
        run: |
          sudo apt-get update
          sudo apt install apt-transport-https
          sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
          sudo apt-key add openvpn-repo-pkg-key.pub
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
          sudo apt update
          sudo apt install openvpn3

      - name: Start Open VPN 3
        run: |
          openvpn3 session-start --config .github/vpn.ovpn

      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
        id: get_branch

      - name: Deploy
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy:local ${{ github.event.inputs.stage }} -vv --branch=${{ steps.get_branch.outputs.branch_name }}

      - name: Disconnect Open VPN
        if: always()
        run: openvpn3 session-manage --disconnect --config .github/vpn.ovpn
