name: Deploy to Vapor

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli

      - name: Deploy Environment
        run: vapor deploy ${{ env.APP_ENV }} --commit="${{ github.sha }}"
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
          APP_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
